[project]
name = "pizza-lever"
version = "0.1.0"
description = "A lever for pizza"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.24.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
